### PR TITLE
fix ddl filename version

### PR DESCRIPTION
**Pull request by camshaft**
`"_1"` was hardcoded as the version for output files. This uses the `SelfDescInfo.version` instead

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @camshaft ! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by camshaft** [comment]
done

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by alexanderdean** [comment]
Thanks, closing now we have #129

**Pull request closed without merging**
