### PR TITLE
Release/0.6.2

### PR DESCRIPTION
**Pull request by chuwy**
Opening new PR, since github doesn't allow me reopen it with force-pushed branch #158

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @chuwy - the PR looks good but I'm not convinced by this commit message:

     Fixed incorrect type suggestion for integer with null (closes #157) 

I think it would be better if that ticket was renamed to "Bump schema-dll library to 0.3.1", because that is a better description of that commit, and the library bump fixes a couple of other things too...

**Comment by chuwy** [comment]
@alexanderdean absolutely agree.

**Comment by chuwy** [comment]
@alexanderdean fixed.

**Comment by alexanderdean** [comment]
This is released! @chuwy please add a Discourse post for this on Monday (mentioning the schema-ddl release too)...

**Pull request merged**
